# Generated by Django 5.2.8 on 2025-11-23 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gen',
                'verbose_name_plural': 'Genes',
                'db_table': 'gene',
                'ordering': ['symbol'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Otro', 'Otro')], default='Otro', max_length=10)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Seguimiento', 'Seguimiento'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('reference_base', models.CharField(blank=True, max_length=1, null=True)),
                ('alternate_base', models.CharField(blank=True, max_length=1, null=True)),
                ('impact', models.CharField(choices=[('Missense', 'Missense'), ('Frameshift', 'Frameshift'), ('Nonsense', 'Nonsense'), ('Silent', 'Silent'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('gene', models.ForeignKey(db_column='gene_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genetics.gene')),
            ],
            options={
                'verbose_name': 'Variante Genética',
                'verbose_name_plural': 'Variantes Genéticas',
                'db_table': 'genetic_variant',
                'ordering': ['chromosome', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_date', models.DateField()),
                ('allele_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_reports', to='genetics.patient')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='genetics.geneticvariant')),
            ],
            options={
                'verbose_name': 'Reporte de Variante del Paciente',
                'verbose_name_plural': 'Reportes de Variantes de Pacientes',
                'db_table': 'patient_variant_report',
                'ordering': ['-detection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='geneticvariant',
            index=models.Index(fields=['chromosome', 'position'], name='genetic_var_chromos_dc3868_idx'),
        ),
        migrations.AddIndex(
            model_name='geneticvariant',
            index=models.Index(fields=['gene', 'impact'], name='genetic_var_gene_id_427fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvariantreport',
            index=models.Index(fields=['patient', 'detection_date'], name='patient_var_patient_c16165_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvariantreport',
            index=models.Index(fields=['variant', 'patient'], name='patient_var_variant_ce3939_idx'),
        ),
    ]
