apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: genosentinel
type: Opaque
data:
  # root password: 12345678 (base64: MTIzNDU2Nzg=)
  mysql-root-password: MTIzNDU2Nzg=
  # db password: 12345678 (base64: MTIzNDU2Nzg=)
  mysql-password: MTIzNDU2Nzg=